version: '3.1'
services:
  broker:
    image: broker
    restart: always
    container_name: broker
    ports:
      - 25565:25565
    volumes:
      - "./configs/broker/config.json:/app/configs/broker/config.json"
      - "./tmp:/app/tmp"
